"""
Built-in Themes Definitions for AnkiForge Style Engine.
Contient l'ensemble des 24 thèmes officiels (12 Sombres & 12 Clairs) organisés en 12 Familles de Thèmes bivalentes.
"""

from dataclasses import dataclass

from ankiforge.ui.style_engine.theme_profile import ThemeProfile


@dataclass(frozen=True)
class ThemeFamily:
    """Représente une famille de thème bivalente (possédant une déclinaison Sombre et Claire)."""

    id: str
    name: str
    icon: str
    description: str
    dark_theme: ThemeProfile
    light_theme: ThemeProfile


# ==============================================================================
# 🌙 THÈMES SOMBRES (DARK THEMES) — 12 PROFILS
# ==============================================================================

JETBRAINS_DARK = ThemeProfile(
    id="ide",
    name="JetBrains Dark (Défaut IDE)",
    description="Style IDE sombre haute densité, contraste précis, bordures 1px et accent indigo.",
    is_dark=True,
    bg_main="#0f1115",
    bg_sidebar="#16181d",
    bg_panel="#1e2128",
    bg_input="#1a1d24",
    bg_hover="#2d313a",
    bg_active="rgba(99, 102, 241, 0.14)",
    accent_primary="#6366f1",
    accent_hover="#4f46e5",
    accent_glow="rgba(99, 102, 241, 0.4)",
    text_primary="#f8fafc",
    text_secondary="#94a3b8",
    text_muted="#64748b",
    border_color="#2d313a",
    border_light="rgba(255, 255, 255, 0.04)",
    border_focus="#6366f1",
    color_blue="#3b82f6",
    color_green="#10b981",
    color_yellow="#f59e0b",
    color_red="#ef4444",
    color_purple="#6366f1",
    radius_sm=6,
    radius_md=10,
    radius_lg=16,
)

EMERALD_DASHBOARD = ThemeProfile(
    id="dashboard",
    name="Modern SaaS Emerald",
    description="Style portail contemporain bleu nuit profond, cartes lumineuses et touches vert émeraude.",
    is_dark=True,
    bg_main="#0b0f19",
    bg_sidebar="#111827",
    bg_panel="#1f2937",
    bg_input="#111827",
    bg_hover="#374151",
    bg_active="rgba(16, 185, 129, 0.16)",
    accent_primary="#10b981",
    accent_hover="#059669",
    accent_glow="rgba(16, 185, 129, 0.4)",
    text_primary="#f9fafb",
    text_secondary="#9ca3af",
    text_muted="#6b7280",
    border_color="#374151",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#10b981",
    color_blue="#38bdf8",
    color_green="#10b981",
    color_yellow="#facc15",
    color_red="#f87171",
    color_purple="#a855f7",
    radius_sm=8,
    radius_md=12,
    radius_lg=16,
)

CYBER_GLASS = ThemeProfile(
    id="glassmorphism",
    name="Cyber Amethyst Glass",
    description="Style moderne semi-translucide effet verre dépoli, reflets subtils et touches néon violettes.",
    is_dark=True,
    bg_main="#08090d",
    bg_sidebar="rgba(26, 29, 45, 0.85)",
    bg_panel="rgba(22, 25, 38, 0.75)",
    bg_input="rgba(16, 18, 28, 0.80)",
    bg_hover="rgba(255, 255, 255, 0.08)",
    bg_active="rgba(192, 132, 252, 0.20)",
    accent_primary="#c084fc",
    accent_hover="#a855f7",
    accent_glow="rgba(192, 132, 252, 0.45)",
    text_primary="#f8fafc",
    text_secondary="#94a3b8",
    text_muted="#64748b",
    border_color="rgba(192, 132, 252, 0.25)",
    border_light="rgba(255, 255, 255, 0.08)",
    border_focus="#c084fc",
    color_blue="#60a5fa",
    color_green="#34d399",
    color_yellow="#fde047",
    color_red="#f87171",
    color_purple="#c084fc",
    radius_sm=10,
    radius_md=16,
    radius_lg=22,
)

MACOS_DARK = ThemeProfile(
    id="macos",
    name="Apple macOS Native Dark",
    description="Style natif macOS gris titane avec typographie aérée, boutons arrondis et bleu Cupertino.",
    is_dark=True,
    bg_main="#1e1e24",
    bg_sidebar="#25262e",
    bg_panel="#282932",
    bg_input="#22232a",
    bg_hover="#363844",
    bg_active="rgba(10, 132, 255, 0.18)",
    accent_primary="#0a84ff",
    accent_hover="#0071e3",
    accent_glow="rgba(10, 132, 255, 0.35)",
    text_primary="#ffffff",
    text_secondary="#a1a1aa",
    text_muted="#71717a",
    border_color="rgba(255, 255, 255, 0.10)",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#0a84ff",
    color_blue="#0a84ff",
    color_green="#30d158",
    color_yellow="#ffd60a",
    color_red="#ff453a",
    color_purple="#bf5af2",
    radius_sm=8,
    radius_md=12,
    radius_lg=18,
)
MACOS_SLATE = MACOS_DARK

SYNTHWAVE_84 = ThemeProfile(
    id="synthwave_84",
    name="Synthwave '84 Cyberpunk",
    description="Rétro-futurisme années 80, rose néon vibrant, reflets jaunes et horizon crépusculaire.",
    is_dark=True,
    bg_main="#1a1025",
    bg_sidebar="#241738",
    bg_panel="#2e1f47",
    bg_input="#271a3d",
    bg_hover="#3d2b5e",
    bg_active="rgba(255, 126, 219, 0.20)",
    accent_primary="#ff7edb",
    accent_hover="#f92aad",
    accent_glow="rgba(255, 126, 219, 0.45)",
    text_primary="#f8f8f2",
    text_secondary="#f1a5e4",
    text_muted="#b893ba",
    border_color="#4a356d",
    border_light="rgba(255, 255, 255, 0.06)",
    border_focus="#ff7edb",
    color_blue="#36f9f6",
    color_green="#72f1b8",
    color_yellow="#fede5d",
    color_red="#fe4450",
    color_purple="#ff7edb",
    radius_sm=8,
    radius_md=12,
    radius_lg=16,
)

MONOKAI_PRO = ThemeProfile(
    id="monokai_pro",
    name="Monokai Pro High Contrast",
    description="Confort de lecture haute précision pour développeurs, fond noir feutré et jaune éclatant.",
    is_dark=True,
    bg_main="#19181a",
    bg_sidebar="#221f22",
    bg_panel="#2d2a2e",
    bg_input="#272428",
    bg_hover="#3a363b",
    bg_active="rgba(255, 216, 102, 0.18)",
    accent_primary="#ffd866",
    accent_hover="#e6c35c",
    accent_glow="rgba(255, 216, 102, 0.4)",
    text_primary="#fcfcfa",
    text_secondary="#939293",
    text_muted="#727072",
    border_color="#403e41",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#ffd866",
    color_blue="#78dce8",
    color_green="#a9dc76",
    color_yellow="#ffd866",
    color_red="#ff6188",
    color_purple="#ab9df2",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

CATPPUCCIN_MOCHA = ThemeProfile(
    id="catppuccin_mocha",
    name="Catppuccin Mocha Pastel",
    description="Palette pastel apaisante et chaleureuse pour les sessions de révision prolongées.",
    is_dark=True,
    bg_main="#1e1e2e",
    bg_sidebar="#181825",
    bg_panel="#313244",
    bg_input="#25263a",
    bg_hover="#45475a",
    bg_active="rgba(137, 180, 250, 0.18)",
    accent_primary="#89b4fa",
    accent_hover="#74c7ec",
    accent_glow="rgba(137, 180, 250, 0.35)",
    text_primary="#cdd6f4",
    text_secondary="#bac2de",
    text_muted="#a6adc8",
    border_color="#45475a",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#89b4fa",
    color_blue="#89b4fa",
    color_green="#a6e3a1",
    color_yellow="#f9e2af",
    color_red="#f38ba8",
    color_purple="#cba6f7",
    radius_sm=8,
    radius_md=12,
    radius_lg=16,
)

NORD_POLAR = ThemeProfile(
    id="nord_polar",
    name="Nord Polar Arctic",
    description="Harmonie arctique scandinave, tons ardoise froids et cyan polaire pur.",
    is_dark=True,
    bg_main="#242933",
    bg_sidebar="#1e222a",
    bg_panel="#2e3440",
    bg_input="#282e39",
    bg_hover="#3b4252",
    bg_active="rgba(136, 192, 208, 0.18)",
    accent_primary="#88c0d0",
    accent_hover="#81a1c1",
    accent_glow="rgba(136, 192, 208, 0.35)",
    text_primary="#eceff4",
    text_secondary="#d8dee9",
    text_muted="#4c566a",
    border_color="#434c5e",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#88c0d0",
    color_blue="#81a1c1",
    color_green="#a3be8c",
    color_yellow="#ebcb8b",
    color_red="#bf616a",
    color_purple="#b48ead",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

DRACULA_OFFICIAL = ThemeProfile(
    id="dracula_official",
    name="Dracula Official Gothic",
    description="Contraste sombre culte, fond violet profond, mauve vampire et accents vibrants.",
    is_dark=True,
    bg_main="#21222c",
    bg_sidebar="#191a21",
    bg_panel="#282a36",
    bg_input="#242631",
    bg_hover="#343746",
    bg_active="rgba(189, 147, 249, 0.18)",
    accent_primary="#bd93f9",
    accent_hover="#ff79c6",
    accent_glow="rgba(189, 147, 249, 0.4)",
    text_primary="#f8f8f2",
    text_secondary="#bfbfbf",
    text_muted="#6272a4",
    border_color="#44475a",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#bd93f9",
    color_blue="#8be9fd",
    color_green="#50fa7b",
    color_yellow="#f1fa8c",
    color_red="#ff5555",
    color_purple="#bd93f9",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

TOKYO_NIGHT = ThemeProfile(
    id="tokyo_night",
    name="Tokyo Night Neon",
    description="Ciel nocturne de Tokyo avec reflets néons cyan et bleu profond.",
    is_dark=True,
    bg_main="#16161e",
    bg_sidebar="#13141a",
    bg_panel="#1f2335",
    bg_input="#1a1b26",
    bg_hover="#292e42",
    bg_active="rgba(122, 162, 247, 0.18)",
    accent_primary="#7aa2f7",
    accent_hover="#2ac3de",
    accent_glow="rgba(122, 162, 247, 0.35)",
    text_primary="#c0caf5",
    text_secondary="#9aa5ce",
    text_muted="#565f89",
    border_color="#292e42",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#7aa2f7",
    color_blue="#7aa2f7",
    color_green="#9ece6a",
    color_yellow="#e0af68",
    color_red="#f7768e",
    color_purple="#bb9af7",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

SOLARIZED_DARK = ThemeProfile(
    id="solarized_dark",
    name="Solarized Dark Amber",
    description="Précision colorimétrique éprouvée, fond bleu canard et or solaire.",
    is_dark=True,
    bg_main="#001e26",
    bg_sidebar="#00141a",
    bg_panel="#002b36",
    bg_input="#00252e",
    bg_hover="#073642",
    bg_active="rgba(181, 137, 0, 0.18)",
    accent_primary="#b58900",
    accent_hover="#268bd2",
    accent_glow="rgba(181, 137, 0, 0.4)",
    text_primary="#93a1a1",
    text_secondary="#839496",
    text_muted="#586e75",
    border_color="#073642",
    border_light="rgba(255, 255, 255, 0.04)",
    border_focus="#b58900",
    color_blue="#268bd2",
    color_green="#859900",
    color_yellow="#b58900",
    color_red="#dc322f",
    color_purple="#6c71c4",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

ONE_DARK_PRO = ThemeProfile(
    id="one_dark_pro",
    name="One Dark Pro Atom",
    description="Le standard Atom/VSCode épuré, fond charbon neutre et cyan équilibré.",
    is_dark=True,
    bg_main="#1e2227",
    bg_sidebar="#181a1f",
    bg_panel="#282c34",
    bg_input="#21252b",
    bg_hover="#353b45",
    bg_active="rgba(97, 175, 239, 0.18)",
    accent_primary="#61afef",
    accent_hover="#4fa0e0",
    accent_glow="rgba(97, 175, 239, 0.35)",
    text_primary="#abb2bf",
    text_secondary="#828997",
    text_muted="#5c6370",
    border_color="#3b4048",
    border_light="rgba(255, 255, 255, 0.05)",
    border_focus="#61afef",
    color_blue="#61afef",
    color_green="#98c379",
    color_yellow="#e5c07b",
    color_red="#e06c75",
    color_purple="#c678dd",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)


# ==============================================================================
# ☀️ THÈMES CLAIRS (LIGHT THEMES) — 12 PROFILS ASSORTIS
# ==============================================================================

JETBRAINS_LIGHT = ThemeProfile(
    id="jetbrains_light",
    name="JetBrains Light (IDE Clair)",
    description="Style IDE clair haute lisibilité, fond albâtre, typographie dense et accent indigo.",
    is_dark=False,
    bg_main="#f5f6f8",
    bg_sidebar="#ebeef2",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#e2e6ea",
    bg_active="rgba(79, 70, 229, 0.12)",
    accent_primary="#4f46e5",
    accent_hover="#4338ca",
    accent_glow="rgba(79, 70, 229, 0.25)",
    text_primary="#1f2328",
    text_secondary="#57606a",
    text_muted="#8c959f",
    border_color="#d0d7de",
    border_light="#f0f2f5",
    border_focus="#4f46e5",
    color_blue="#0969da",
    color_green="#1a7f37",
    color_yellow="#9a6700",
    color_red="#cf222e",
    color_purple="#8250df",
    radius_sm=6,
    radius_md=10,
    radius_lg=16,
)

EMERALD_LIGHT = ThemeProfile(
    id="emerald_light",
    name="Modern SaaS Emerald Light",
    description="Tableau de bord lumineux émeraude, vert vivifiant et cartes blanches épurées.",
    is_dark=False,
    bg_main="#f0fdf4",
    bg_sidebar="#dcfce7",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#bbf7d0",
    bg_active="rgba(5, 150, 105, 0.14)",
    accent_primary="#059669",
    accent_hover="#047857",
    accent_glow="rgba(5, 150, 105, 0.25)",
    text_primary="#064e3b",
    text_secondary="#047857",
    text_muted="#65a30d",
    border_color="#bbf7d0",
    border_light="#ecfdf5",
    border_focus="#059669",
    color_blue="#0284c7",
    color_green="#059669",
    color_yellow="#d97706",
    color_red="#dc2626",
    color_purple="#7c3aed",
    radius_sm=8,
    radius_md=12,
    radius_lg=16,
)

CYBER_GLASS_LIGHT = ThemeProfile(
    id="cyber_glass_light",
    name="Cyber Crystal Glass Light",
    description="Effet verre givré translucide clair, reflets cristal et touches d'améthyste lumineuse.",
    is_dark=False,
    bg_main="#f8fafc",
    bg_sidebar="rgba(241, 245, 249, 0.85)",
    bg_panel="rgba(255, 255, 255, 0.90)",
    bg_input="rgba(255, 255, 255, 0.95)",
    bg_hover="rgba(192, 132, 252, 0.15)",
    bg_active="rgba(168, 85, 247, 0.16)",
    accent_primary="#9333ea",
    accent_hover="#7e22ce",
    accent_glow="rgba(168, 85, 247, 0.3)",
    text_primary="#0f172a",
    text_secondary="#334155",
    text_muted="#64748b",
    border_color="rgba(168, 85, 247, 0.25)",
    border_light="rgba(255, 255, 255, 0.6)",
    border_focus="#9333ea",
    color_blue="#0284c7",
    color_green="#059669",
    color_yellow="#d97706",
    color_red="#dc2626",
    color_purple="#9333ea",
    radius_sm=10,
    radius_md=16,
    radius_lg=22,
)

MACOS_LIGHT = ThemeProfile(
    id="macos_light",
    name="Apple macOS Native Light",
    description="Élégance native macOS claire, fond blanc pur, boutons gris clair et bleu Cupertino.",
    is_dark=False,
    bg_main="#f6f6f6",
    bg_sidebar="#ececec",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#e0e0e0",
    bg_active="rgba(0, 113, 227, 0.12)",
    accent_primary="#0071e3",
    accent_hover="#0077ed",
    accent_glow="rgba(0, 113, 227, 0.25)",
    text_primary="#1d1d1f",
    text_secondary="#6e6e73",
    text_muted="#86868b",
    border_color="#d2d2d7",
    border_light="#e8e8ed",
    border_focus="#0071e3",
    color_blue="#0071e3",
    color_green="#28cd41",
    color_yellow="#ffcc00",
    color_red="#ff3b30",
    color_purple="#af52de",
    radius_sm=8,
    radius_md=12,
    radius_lg=18,
)

SYNTHWAVE_LIGHT = ThemeProfile(
    id="synthwave_light",
    name="Synthwave '84 Sunset Light",
    description="Ambiance coucher de soleil rétro années 80, fond rosé lumineux, accents fuchsia et violet.",
    is_dark=False,
    bg_main="#fdf4f8",
    bg_sidebar="#fce7f3",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#fbcfe8",
    bg_active="rgba(217, 70, 239, 0.15)",
    accent_primary="#d946ef",
    accent_hover="#c026d3",
    accent_glow="rgba(217, 70, 239, 0.3)",
    text_primary="#701a75",
    text_secondary="#86198f",
    text_muted="#a21caf",
    border_color="#f5d0fe",
    border_light="#fdf4f8",
    border_focus="#d946ef",
    color_blue="#0284c7",
    color_green="#059669",
    color_yellow="#d97706",
    color_red="#e11d48",
    color_purple="#d946ef",
    radius_sm=8,
    radius_md=12,
    radius_lg=16,
)

MONOKAI_LIGHT = ThemeProfile(
    id="monokai_light",
    name="Monokai Pro Light",
    description="Style Monokai clair haute lisibilité, fond ivoire moderne et accents or chaud/ambre.",
    is_dark=False,
    bg_main="#faf8f5",
    bg_sidebar="#f4f1ea",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#eae4d8",
    bg_active="rgba(217, 119, 6, 0.14)",
    accent_primary="#d97706",
    accent_hover="#b45309",
    accent_glow="rgba(217, 119, 6, 0.3)",
    text_primary="#292524",
    text_secondary="#57534e",
    text_muted="#78716c",
    border_color="#e7e0d3",
    border_light="#faf8f5",
    border_focus="#d97706",
    color_blue="#0284c7",
    color_green="#16a34a",
    color_yellow="#d97706",
    color_red="#dc2626",
    color_purple="#7c3aed",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

CATPPUCCIN_LATTE = ThemeProfile(
    id="catppuccin_latte",
    name="Catppuccin Latte Light",
    description="Douceur pastel claire et apaisante avec accents bleu saphir et mauve tendre.",
    is_dark=False,
    bg_main="#eff1f5",
    bg_sidebar="#e6e9ef",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#dce0e8",
    bg_active="rgba(30, 102, 245, 0.12)",
    accent_primary="#1e66f5",
    accent_hover="#04a5e5",
    accent_glow="rgba(30, 102, 245, 0.25)",
    text_primary="#4c4f69",
    text_secondary="#6c6f85",
    text_muted="#9ca0b0",
    border_color="#ccd0da",
    border_light="#e6e9ef",
    border_focus="#1e66f5",
    color_blue="#1e66f5",
    color_green="#40a02b",
    color_yellow="#df8e1d",
    color_red="#d20f39",
    color_purple="#8839ef",
    radius_sm=8,
    radius_md=12,
    radius_lg=16,
)

NORD_LIGHT = ThemeProfile(
    id="nord_light",
    name="Nord Snow Storm Light",
    description="Clarté scandinave épurée, fond blanc neige et accents bleu ardoise polaire.",
    is_dark=False,
    bg_main="#eceff4",
    bg_sidebar="#e5e9f0",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#d8dee9",
    bg_active="rgba(94, 129, 172, 0.14)",
    accent_primary="#5e81ac",
    accent_hover="#81a1c1",
    accent_glow="rgba(94, 129, 172, 0.25)",
    text_primary="#2e3440",
    text_secondary="#4c566a",
    text_muted="#9aa3b2",
    border_color="#d8dee9",
    border_light="#e5e9f0",
    border_focus="#5e81ac",
    color_blue="#5e81ac",
    color_green="#a3be8c",
    color_yellow="#ebcb8b",
    color_red="#bf616a",
    color_purple="#b48ead",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

DRACULA_LIGHT = ThemeProfile(
    id="dracula_light",
    name="Dracula Alucard Light",
    description="Pendant clair gothique élégant de Dracula, fond brume mauve et accents pourpre vampire.",
    is_dark=False,
    bg_main="#f7f6fb",
    bg_sidebar="#eeeaf8",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#e2daf4",
    bg_active="rgba(147, 51, 234, 0.14)",
    accent_primary="#9333ea",
    accent_hover="#7e22ce",
    accent_glow="rgba(147, 51, 234, 0.3)",
    text_primary="#2e1065",
    text_secondary="#581c87",
    text_muted="#7e22ce",
    border_color="#ddd6fe",
    border_light="#f7f6fb",
    border_focus="#9333ea",
    color_blue="#2563eb",
    color_green="#16a34a",
    color_yellow="#ca8a04",
    color_red="#e11d48",
    color_purple="#9333ea",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

TOKYO_DAY = ThemeProfile(
    id="tokyo_day",
    name="Tokyo Day Morning",
    description="Lumière matinale tokyoïte avec accents bleu cobalt et ardoise claire.",
    is_dark=False,
    bg_main="#e1e2e7",
    bg_sidebar="#d5d6db",
    bg_panel="#f8f9fa",
    bg_input="#ffffff",
    bg_hover="#cfd0d6",
    bg_active="rgba(52, 84, 138, 0.14)",
    accent_primary="#34548a",
    accent_hover="#2e7de9",
    accent_glow="rgba(52, 84, 138, 0.25)",
    text_primary="#343b58",
    text_secondary="#565a6e",
    text_muted="#8f93a2",
    border_color="#c8cbd2",
    border_light="#e1e2e7",
    border_focus="#34548a",
    color_blue="#34548a",
    color_green="#385f0f",
    color_yellow="#8c6c3e",
    color_red="#8c4351",
    color_purple="#5a4a78",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

SOLARIZED_LIGHT = ThemeProfile(
    id="solarized_light",
    name="Solarized Light Parchment",
    description="Fond parchemin jaune pâle réconfortant pour les yeux et accents dorés/cyan.",
    is_dark=False,
    bg_main="#fdf6e3",
    bg_sidebar="#eee8d5",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#e0d7be",
    bg_active="rgba(181, 137, 0, 0.15)",
    accent_primary="#b58900",
    accent_hover="#cb4b16",
    accent_glow="rgba(181, 137, 0, 0.3)",
    text_primary="#073642",
    text_secondary="#586e75",
    text_muted="#93a1a1",
    border_color="#eee8d5",
    border_light="#fdf6e3",
    border_focus="#b58900",
    color_blue="#268bd2",
    color_green="#859900",
    color_yellow="#b58900",
    color_red="#dc322f",
    color_purple="#6c71c4",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)

ONE_LIGHT_PRO = ThemeProfile(
    id="one_light_pro",
    name="One Light Pro Atom",
    description="Clarté moderne Atom/VSCode, fond blanc cassé et accents bleu cyan équilibrés.",
    is_dark=False,
    bg_main="#fafafa",
    bg_sidebar="#f0f0f0",
    bg_panel="#ffffff",
    bg_input="#ffffff",
    bg_hover="#e5e5e6",
    bg_active="rgba(1, 132, 188, 0.12)",
    accent_primary="#0184bc",
    accent_hover="#4078f2",
    accent_glow="rgba(1, 132, 188, 0.25)",
    text_primary="#383a42",
    text_secondary="#696c77",
    text_muted="#a0a1a7",
    border_color="#dbdbdc",
    border_light="#f0f0f0",
    border_focus="#0184bc",
    color_blue="#4078f2",
    color_green="#50a14f",
    color_yellow="#c18401",
    color_red="#e45649",
    color_purple="#a626a4",
    radius_sm=6,
    radius_md=10,
    radius_lg=14,
)


# ==============================================================================
# 🎨 LES 12 FAMILLES DE THÈMES (BIVALENTES SOMBRE / CLAIR)
# ==============================================================================

THEME_FAMILIES: dict[str, ThemeFamily] = {
    "jetbrains": ThemeFamily(
        id="jetbrains",
        name="JetBrains IDE",
        icon="ph.code",
        description="Style IDE haute densité avec accent Indigo vif.",
        dark_theme=JETBRAINS_DARK,
        light_theme=JETBRAINS_LIGHT,
    ),
    "emerald": ThemeFamily(
        id="emerald",
        name="Modern SaaS Emerald",
        icon="ph.chart-line-up",
        description="Tableau de bord contemporain avec accent vert Émeraude.",
        dark_theme=EMERALD_DASHBOARD,
        light_theme=EMERALD_LIGHT,
    ),
    "glassmorphism": ThemeFamily(
        id="glassmorphism",
        name="Cyber Glass",
        icon="ph.sparkle",
        description="Esthétique verre givré translucide et reflets Améthyste.",
        dark_theme=CYBER_GLASS,
        light_theme=CYBER_GLASS_LIGHT,
    ),
    "macos": ThemeFamily(
        id="macos",
        name="Apple macOS Native",
        icon="ph.apple-logo",
        description="Épure et élégance Apple avec accent Bleu Cupertino.",
        dark_theme=MACOS_DARK,
        light_theme=MACOS_LIGHT,
    ),
    "synthwave": ThemeFamily(
        id="synthwave",
        name="Synthwave '84",
        icon="ph.sun-horizon",
        description="Rétro-futurisme néon et ambiance coucher de soleil.",
        dark_theme=SYNTHWAVE_84,
        light_theme=SYNTHWAVE_LIGHT,
    ),
    "monokai": ThemeFamily(
        id="monokai",
        name="Monokai Pro",
        icon="ph.lightning",
        description="Contraste précis de référence avec accent Or / Ambre.",
        dark_theme=MONOKAI_PRO,
        light_theme=MONOKAI_LIGHT,
    ),
    "catppuccin": ThemeFamily(
        id="catppuccin",
        name="Catppuccin Pastel",
        icon="ph.coffee",
        description="Harmonie pastel apaisante (Mocha & Latte).",
        dark_theme=CATPPUCCIN_MOCHA,
        light_theme=CATPPUCCIN_LATTE,
    ),
    "nord": ThemeFamily(
        id="nord",
        name="Nord Arctic",
        icon="ph.snowflake",
        description="Clarté scandinave ardoise et cyan (Polar & Snow Storm).",
        dark_theme=NORD_POLAR,
        light_theme=NORD_LIGHT,
    ),
    "dracula": ThemeFamily(
        id="dracula",
        name="Dracula / Alucard",
        icon="ph.moon-stars",
        description="Style gothique vampire sombre et brume mauve claire.",
        dark_theme=DRACULA_OFFICIAL,
        light_theme=DRACULA_LIGHT,
    ),
    "tokyo": ThemeFamily(
        id="tokyo",
        name="Tokyo Night / Day",
        icon="ph.buildings",
        description="Lumières tokyoïtes nocturnes et éclat matinal.",
        dark_theme=TOKYO_NIGHT,
        light_theme=TOKYO_DAY,
    ),
    "solarized": ThemeFamily(
        id="solarized",
        name="Solarized",
        icon="ph.sun",
        description="Précision colorimétrique éprouvée bleu canard et parchemin.",
        dark_theme=SOLARIZED_DARK,
        light_theme=SOLARIZED_LIGHT,
    ),
    "one_pro": ThemeFamily(
        id="one_pro",
        name="One Pro Atom",
        icon="ph.atom",
        description="Le standard Atom/VSCode neutre et équilibré.",
        dark_theme=ONE_DARK_PRO,
        light_theme=ONE_LIGHT_PRO,
    ),
}


# ==============================================================================
# 📚 REGISTRE DE TOUS LES THÈMES INTÉGRÉS & ALIAS
# ==============================================================================

BUILTIN_THEMES: dict[str, ThemeProfile] = {
    # Dark themes
    "ide": JETBRAINS_DARK,
    "jetbrains_dark": JETBRAINS_DARK,
    "dashboard": EMERALD_DASHBOARD,
    "emerald_dashboard": EMERALD_DASHBOARD,
    "glassmorphism": CYBER_GLASS,
    "cyber_glass": CYBER_GLASS,
    "macos": MACOS_DARK,
    "macos_dark": MACOS_DARK,
    "synthwave_84": SYNTHWAVE_84,
    "synthwave": SYNTHWAVE_84,
    "monokai_pro": MONOKAI_PRO,
    "monokai": MONOKAI_PRO,
    "catppuccin_mocha": CATPPUCCIN_MOCHA,
    "catppuccin": CATPPUCCIN_MOCHA,
    "nord_polar": NORD_POLAR,
    "nord": NORD_POLAR,
    "dracula_official": DRACULA_OFFICIAL,
    "dracula": DRACULA_OFFICIAL,
    "tokyo_night": TOKYO_NIGHT,
    "tokyo": TOKYO_NIGHT,
    "solarized_dark": SOLARIZED_DARK,
    "solarized": SOLARIZED_DARK,
    "one_dark_pro": ONE_DARK_PRO,
    "one_pro": ONE_DARK_PRO,
    # Light themes
    "jetbrains_light": JETBRAINS_LIGHT,
    "emerald_light": EMERALD_LIGHT,
    "cyber_glass_light": CYBER_GLASS_LIGHT,
    "macos_light": MACOS_LIGHT,
    "synthwave_light": SYNTHWAVE_LIGHT,
    "synthwave_84_light": SYNTHWAVE_LIGHT,
    "monokai_light": MONOKAI_LIGHT,
    "catppuccin_latte": CATPPUCCIN_LATTE,
    "nord_light": NORD_LIGHT,
    "dracula_light": DRACULA_LIGHT,
    "tokyo_day": TOKYO_DAY,
    "solarized_light": SOLARIZED_LIGHT,
    "one_light_pro": ONE_LIGHT_PRO,
}


def get_theme_families() -> list[ThemeFamily]:
    """Retourne la liste des 12 familles de thèmes bivalentes."""
    return list(THEME_FAMILIES.values())


def get_family_for_theme(theme_id: str) -> ThemeFamily | None:
    """Retrouve la famille de thème correspondante à un theme_id donné."""
    theme_id_clean = theme_id.lower().strip()
    if theme_id_clean in THEME_FAMILIES:
        return THEME_FAMILIES[theme_id_clean]

    for fam in THEME_FAMILIES.values():
        if fam.dark_theme.id == theme_id_clean or fam.light_theme.id == theme_id_clean:
            return fam
        # Check aliases
        if theme_id_clean in ("ide", "jetbrains_dark", "jetbrains_light") and fam.id == "jetbrains":
            return fam
        if theme_id_clean in ("dashboard", "emerald_dashboard", "emerald_light") and fam.id == "emerald":
            return fam
        if theme_id_clean in ("glassmorphism", "cyber_glass", "cyber_glass_light") and fam.id == "glassmorphism":
            return fam
        if theme_id_clean in ("macos", "macos_dark", "macos_light") and fam.id == "macos":
            return fam
        if theme_id_clean in ("synthwave_84", "synthwave_light", "synthwave_84_light") and fam.id == "synthwave":
            return fam
        if theme_id_clean in ("monokai_pro", "monokai_light") and fam.id == "monokai":
            return fam
        if theme_id_clean in ("catppuccin_mocha", "catppuccin_latte") and fam.id == "catppuccin":
            return fam
        if theme_id_clean in ("nord_polar", "nord_light") and fam.id == "nord":
            return fam
        if theme_id_clean in ("dracula_official", "dracula_light") and fam.id == "dracula":
            return fam
        if theme_id_clean in ("tokyo_night", "tokyo_day") and fam.id == "tokyo":
            return fam
        if theme_id_clean in ("solarized_dark", "solarized_light") and fam.id == "solarized":
            return fam
        if theme_id_clean in ("one_dark_pro", "one_light_pro") and fam.id == "one_pro":
            return fam

    return None


def get_unique_builtin_themes() -> list[ThemeProfile]:
    """Retourne la liste des thèmes intégrés sans doublons d'alias (12 sombres + 12 clairs)."""
    seen_ids = set()
    unique_list = []
    preferred_order = [
        # Dark
        JETBRAINS_DARK,
        EMERALD_DASHBOARD,
        CYBER_GLASS,
        MACOS_DARK,
        SYNTHWAVE_84,
        MONOKAI_PRO,
        CATPPUCCIN_MOCHA,
        NORD_POLAR,
        DRACULA_OFFICIAL,
        TOKYO_NIGHT,
        SOLARIZED_DARK,
        ONE_DARK_PRO,
        # Light
        JETBRAINS_LIGHT,
        EMERALD_LIGHT,
        CYBER_GLASS_LIGHT,
        MACOS_LIGHT,
        SYNTHWAVE_LIGHT,
        MONOKAI_LIGHT,
        CATPPUCCIN_LATTE,
        NORD_LIGHT,
        DRACULA_LIGHT,
        TOKYO_DAY,
        SOLARIZED_LIGHT,
        ONE_LIGHT_PRO,
    ]
    for theme in preferred_order:
        if theme.id not in seen_ids:
            seen_ids.add(theme.id)
            unique_list.append(theme)
    return unique_list
